# Generated by Django 5.2.14 on 2026-05-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_user_feedback_user_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
