# Generated by Django 5.2.14 on 2026-05-28 11:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_quizresult_user_alter_feedback_user_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(default='+91', max_length=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
