# Generated by Django 5.2.14 on 2026-05-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel'),
        ),
    ]
